# Generated by Django 3.0.8 on 2020-07-29 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_group_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='groups',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='api.Group'),
        ),
    ]
