# Generated by Django 3.0.8 on 2020-08-03 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_note_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='color',
            field=models.CharField(choices=[('primary', 'Blue'), ('secondary', 'Grey'), ('success', 'Green'), ('danger', 'Red'), ('warning', 'Yellow'), ('info', 'Cyan'), ('light', 'Lightgrey'), ('dark', 'Black')], max_length=100),
        ),
        migrations.AlterField(
            model_name='note',
            name='color',
            field=models.CharField(blank=True, choices=[('primary', 'Blue'), ('secondary', 'Grey'), ('success', 'Green'), ('danger', 'Red'), ('warning', 'Yellow'), ('info', 'Cyan'), ('light', 'Lightgrey'), ('dark', 'Black')], max_length=100, null=True),
        ),
    ]
