export const START_LOADING = 'START_LOADING'
export const STOP_LOADING = 'STOP_LOADING'

export const FETCH_NOTES = 'FETCH_NOTES'
export const FETCH_NOTE = 'FETCH_NOTE'
export const EDIT_NOTE = 'EDIT_NOTE'
export const START_EDIT_NOTE = 'START_EDIT_NOTE'
export const STOP_EDIT_NOTE = 'STOP_EDIT_NOTE'
export const DELETE_NOTE = 'DELETE_NOTE'
export const SELECT_NOTE = 'SELECT_NOTE'
export const DESELECT_NOTE = 'DESELECT_NOTE'

export const CHANGE_PAGE = 'CHANGE_PAGE'

export const ERROR_MESSAGE = 'ERROR_MESSAGE'
export const SUCCESS_MESSAGE = 'SUCCESS_MESSAGE'
export const INFO_MESSAGE = 'INFO_MESSAGE'
export const CLEAR_MESSAGE = 'CLEAR_MESSAGE'

export const LOGIN = 'LOGIN'
export const LOGOUT = 'LOGOUT'
export const AUTH_ERROR = 'AUTH_ERROR'
export const LOADING_USER = 'LOADING_USER'
export const USER_LOADED = 'USER_LOADED'

export const SHOW_DELETE_MODAL = 'SHOW_DELETE_MODAL'
export const HIDE_DELETE_MODAL = 'HIDE_DELETE_MODAL'